name: Android Release

on:
  workflow_dispatch:

env:
  WORKING_DIRECTORY: "app"
  BUILD_OFFSET: "100"

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Create version.txt with nuGetVersion
        run: |
          mkdir build_info
          echo -n ${{ env.GITVERSION_SEMVER  }} > build_info/version.txt
          echo -n "$((${{ github.run_number }}+${{ env.BUILD_OFFSET }}))" > build_info/build.txt

      - name: Upload version
        uses: actions/upload-artifact@v2
        with:
          name: build_info
          path: build_info

  deploy:
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get build_info
        uses: actions/download-artifact@v2
        with:
          name: build_info

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: build_info/version.txt

      - name: Read version
        id: build
        uses: juliangruber/read-file-action@v1
        with:
          path: build_info/build.txt

      - name: Update version in .yaml
        run: sed -i 's/0.0.0+0/${{ steps.version.outputs.content }}+${{ steps.build.outputs.content }}/g' pubspec.yaml
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: yaml
          path: ${{env.WORKING_DIRECTORY}}/pubspec.yaml

      - name: create release with artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.version.outputs.content }}+${{env.GITHUB_RUN_NUMBER_WITH_OFFSET}}"
          artifactErrorsFailBuild: true
          artifacts: "${{env.WORKING_DIRECTORY}}/pubspec.yaml"
          token: ${{ secrets.GITHUB_TOKEN }}
