name: Android Release

on:
  workflow_dispatch:

env:
  WORKING_DIRECTORY: "app"
  BUILD_OFFSET: "100"

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Create version.txt with nuGetVersion
        run: |
          mkdir info
          echo -n ${{ env.GITVERSION_SEMVER  }} > info/version.txt
          echo -n "$((${{ github.run_number }}+${{ env.BUILD_OFFSET }}))" > info/build.txt

      - name: Upload version
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: info

  deploy:
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: version

      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: version

      - name: Create new file without newline char from version.txt
        run: tr -d '\n' < version.txt > version1.txt

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version1.txt

      - name: increase build
        run: |
          echo "GITHUB_RUN_NUMBER_WITH_OFFSET=$((${{ github.run_number }}+100))" >> $GITHUB_ENV
          echo "$GITHUB_RUN_NUMBER_WITH_OFFSET"

      - name: print
        run: |
          echo "$GITHUB_RUN_NUMBER_WITH_OFFSET"

      - name: Update version in .yaml
        run: sed -i 's/0.0.0+0/${{ steps.version.outputs.content }}+${{env.GITHUB_RUN_NUMBER_WITH_OFFSET}}/g' pubspec.yaml
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Upload xxx
        uses: actions/upload-artifact@v2
        with:
          name: yaml
          path: app/pubspec.yaml

      - name: create a GitHub release with artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.version.outputs.content }}+${{env.GITHUB_RUN_NUMBER_WITH_OFFSET}}"
          artifactErrorsFailBuild: true
          artifacts: "app/pubspec.yaml"
          token: ${{ secrets.GITHUB_TOKEN }}
